### ISSUE TITLE
D2T relay issue: relays from both sides even if d2t is set. 

### ISSUE THREAD

**Issue by david-lathem** [TediCross/TediCross#435]
```yaml
telegram:
  useFirstNameInsteadOfUsername: false
  colonAfterSenderName: false
  skipOldMessages: true
  sendEmojiWithStickers: true
  useCustomEmojiFilter: false
  replaceAtWithHash: false
  replaceExcessiveSpaces: false
  removeNewlineSpaces: false
  suppressFileTooBigMessages: false
  suppressThisIsPrivateBotMessage: false
  token: dum
discord:
  skipOldMessages: true
  useNickname: false
  replyLength: 100
  maxReplyLines: 2
  suppressThisIsPrivateBotMessage: false
  enableCustomStatus: false
  customStatusMessage: TediCross
  useEmbeds: auto
  token: dum
debug: false
messageTimeoutAmount: 24
messageTimeoutUnit: hours
persistentMessageMap: false
bridges:
  - name: First bridge
    direction: d2t
    telegram:
      chatId: -100219938865
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: false
      crossDeleteOnDiscord: false
    discord:
      channelId: '126717621933021595'
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: false
      crossDeleteOnTelegram: false
      disableWebPreviewOnTelegram: false
      useEmbeds: auto
      ```
      
      Did reset bot token to see , same issue. both and t2d redirection work fine
