### ISSUE TITLE
relayCommands doesn't work

### ISSUE THREAD

**Issue by sven-hash** [TediCross/TediCross#493]
I'm using this configuration to bridge two chats together, on Telegram there's a command that people can execute but I don't what that the `/` appear on Discord. I'm using `relayCommands` and set it to false but it doesn't seems to work, the command is still shared to Discord

```
- name: channelname
    direction: both
    telegram:
      chatId: <id>
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: true
      relayCommands: false
      crossDeleteOnDiscord: true
    discord:
      channelId: <id>
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: true
      crossDeleteOnTelegram: true
      disableWebPreviewOnTelegram: false
      useEmbeds: auto
```
